"# Auto-generated synthesis script" 
"create_project mincpu_opt ./build -part xc7z020clg400-1 -force" 
"add_files {../Hardware/risc_v_cpu_optimized.v ../Hardware/control_unit.v ../Hardware/register_file.v ../Hardware/alu_optimized.v ../Hardware/immediate_gen_optimized.v ../Hardware/branch_unit_optimized.v ../Hardware/multiplier_unit.v ../Hardware/compressed_decoder.v ../Hardware/uart_bootloader.v ../Hardware/instruction_memory.v ../Hardware/data_memory.v ../Hardware/performance_analyzer.v ../Hardware/testbench.v ../Hardware/optimization_test_fixed.v ../Hardware/cpu_config.vh}" 
"set_property top performance_analyzer [current_fileset]" 
"add_files -fileset constrs_1 timing_constraints.xdc" 
"synth_design -top performance_analyzer -part xc7z020clg400-1 -directive AreaOptimized_high" 
"opt_design -directive ExploreArea" 
"place_design -directive ExtraPostPlacementOpt" 
"route_design -directive Explore" 
"report_utilization -file area_report.rpt" 
"report_timing_summary -file timing_report.rpt" 
"exit" 
